FROM golang:1.8
MAINTAINER melsayed mohamed@rancher.com

RUN apt-get update -y && apt-get install -y rsync make
WORKDIR /go/src/k8s.io/
RUN git clone https://github.com/kubernetes/kubernetes
WORKDIR kubernetes
RUN git checkout remotes/origin/release-1.7
RUN make ginkgo generated_files
RUN make WHAT=./test/e2e/e2e.test
ADD https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl /usr/local/bin/
RUN chmod +x /usr/local/bin/kubectl
ENV KUBECONFIG=/kube_config
ENV KUBERNETES_CONFORMANCE_TEST=y
ENV KUBECTL_PATH=/usr/local/bin/kubectl

CMD go run hack/e2e.go -- --provider=skeleton -v --test --test_args="--ginkgo.focus=\[Conformance\]"
